parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  ForwardSo\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  ForwardSo\Http\Controller\:
    resource: '../src/Http/Controller/'
    tags: ['controller.service_arguments']

  ForwardSo\Domain\Service\:
    resource: '../src/Domain/Service'
    tags:
      - { name: tactician.handler, typehints: true }